### ISSUE TITLE
Render particles and infinite loop

### ISSUE THREAD

**Issue by Isafo** [Isafo/Hybrid_Sim#3]
senaste correct divergence branchen kan endast simulera 2 particlar och fastnar i en infinit loop någonstans. Imgui branchen som branchats från denna fungerar. Om felet är känt fixa annars kanske byta och utgå ifrån imgui eller gå tillbaka i commits.

**Comment by Liljan** [comment]
Jaha, ni pushade mot correct divergence nu alltså?

Vi är väl medvetna om att det blir en oändlig loop i divergence eftersom calculate_kv troligen ger fel värde. Vi har inte lyckats rätta felet men jobbar på det. Vi hann inte göra någon issue/todo innan lunch. :)

**Comment by Liljan** [comment]
Vi kan nog visa en äldre commit på mötet ifall det skulle behövas. Alternativt sätta tröskeln "arvg > 0.01" till ett större tal som temporär ful-lösning.

**Comment by chren574** [comment]
När vi ändrar antal partiklar renderas det inget. iaf när vi valde 100st.

**Comment by Isafo** [comment]
allt över 2 partiklar verkar paja. Bara när man har 2 partiklar renderas dem.

**Comment by Pelse862** [comment]
Använd den commit jag gjorde tidigare idag

**Comment by Liljan** [comment]
Ledsen om det blev problem. Jag hade ingen aning om att ni skulle merge:a mot divergence-branchen redan idag. :O
